// @ts-nocheck -- blocks on pg-backed test harness; tracked in _plans/phase2-tests-pg.md
import { describe, it, expect, beforeEach } from "vitest";
import type { AionimaChannelPlugin, ChannelId } from "@agi/plugins";
import { EntityStore, MessageQueue, createDatabase } from "@agi/entity-model";
import type { Database } from "@agi/entity-model";
import { COAChainLogger } from "@agi/coa-chain";

import { GatewayStateMachine } from "./state-machine.js";
import { ChannelRegistry } from "./channel-registry.js";
import { InboundRouter } from "./inbound-router.js";
import { OutboundDispatcher } from "./outbound-dispatcher.js";
import type { OutboundRoute } from "./outbound-dispatcher.js";
import { QueueConsumer } from "./queue-consumer.js";
import type { QueueMessage } from "@agi/entity-model";

// ---------------------------------------------------------------------------
// Mock channel adapter factory
// ---------------------------------------------------------------------------

function createMockPlugin(id: string): AionimaChannelPlugin & { _test: { sentMessages: Array<{ userId: string; content: unknown }>; getMessageHandler: () => ((msg: AionimaChannelPlugin) => Promise<void>) | null; isRunning: () => boolean } } {
  let running = false;
  const sentMessages: Array<{ userId: string; content: unknown }> = [];
  let messageHandler: ((msg: unknown) => Promise<void>) | null = null;

  return {
    id: id as ChannelId,
    meta: { name: `Mock ${id}`, version: "1.0.0" },
    capabilities: { text: true, media: false, voice: false, reactions: false, threads: false, ephemeral: false },
    config: {
      validate: () => true,
      getDefaults: () => ({}),
    },
    gateway: {
      start: async () => { running = true; },
      stop: async () => { running = false; },
      isRunning: () => running,
    },
    outbound: {
      send: async (userId: string, content: unknown) => { sentMessages.push({ userId, content }); },
    },
    messaging: {
      onMessage: (handler: (msg: unknown) => Promise<void>) => { messageHandler = handler; },
    },
    // Expose internals for assertions
    _test: {
      sentMessages,
      getMessageHandler: () => messageHandler as ((msg: AionimaChannelPlugin) => Promise<void>) | null,
      isRunning: () => running,
    },
  } as unknown as AionimaChannelPlugin & { _test: { sentMessages: Array<{ userId: string; content: unknown }>; getMessageHandler: () => ((msg: AionimaChannelPlugin) => Promise<void>) | null; isRunning: () => boolean } };
}

// ---------------------------------------------------------------------------
// In-memory SQLite database factory
// ---------------------------------------------------------------------------

function createTestDb(): Database {
  return createDatabase(":memory:");
}

// ---------------------------------------------------------------------------
// Mock COA logger
//
// COAChainLogger.log() validates entity IDs as COA notation (#E0, #O0, etc.)
// which is incompatible with the ULID IDs generated by EntityStore. For
// InboundRouter and OutboundDispatcher tests, we use a lightweight stub that
// accepts any entity ID and returns deterministic fingerprints.
// ---------------------------------------------------------------------------

interface MockCOARecord {
  resourceId: string;
  entityId: string;
  nodeId: string;
  workType: string;
  fingerprint: string;
}

function createMockCOALogger(): { logger: COAChainLogger; records: MockCOARecord[] } {
  const records: MockCOARecord[] = [];
  let counter = 0;

  const logger = {
    log: (params: { resourceId: string; entityId: string; nodeId: string; workType: string; ref?: string }) => {
      counter++;
      const fingerprint = `${params.resourceId}.ENTITY${counter}.${params.nodeId}.C${String(counter).padStart(3, "0")}`;
      records.push({ ...params, fingerprint });
      return fingerprint;
    },
    getRecord: (fp: string) => records.find((r) => r.fingerprint === fp) ?? null,
    getChain: (entityId: string) => records.filter((r) => r.entityId === entityId),
    getLatestCounter: () => counter,
  } as unknown as COAChainLogger;

  return { logger, records };
}

// ---------------------------------------------------------------------------
// Helper: build a minimal AionimaMessage fixture
// ---------------------------------------------------------------------------

function makeAionimaMessage(channelId: string, channelUserId: string, text = "hello") {
  return {
    id: `msg-${channelId}-${channelUserId}-${Date.now()}`,
    channelId: channelId as ChannelId,
    channelUserId,
    timestamp: new Date().toISOString(),
    content: { type: "text" as const, text },
  };
}

// ---------------------------------------------------------------------------
// 1. GatewayStateMachine tests
// ---------------------------------------------------------------------------

describe.skip("GatewayStateMachine", () => {
  it("starts in initial state passed to constructor", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    expect(sm.getState()).toBe("UNKNOWN");
  });

  it("defaults to UNKNOWN when no initial state provided", () => {
    const sm = new GatewayStateMachine();
    expect(sm.getState()).toBe("UNKNOWN");
  });

  it("allows UNKNOWN → ONLINE transition", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    const result = sm.transition("ONLINE");
    expect(result).toBe(true);
    expect(sm.getState()).toBe("ONLINE");
  });

  it("allows UNKNOWN → LIMBO transition", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    expect(sm.transition("LIMBO")).toBe(true);
    expect(sm.getState()).toBe("LIMBO");
  });

  it("allows UNKNOWN → OFFLINE transition", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    expect(sm.transition("OFFLINE")).toBe(true);
    expect(sm.getState()).toBe("OFFLINE");
  });

  it("allows ONLINE → LIMBO transition", () => {
    const sm = new GatewayStateMachine("ONLINE");
    expect(sm.transition("LIMBO")).toBe(true);
  });

  it("allows ONLINE → UNKNOWN transition", () => {
    const sm = new GatewayStateMachine("ONLINE");
    expect(sm.transition("UNKNOWN")).toBe(true);
  });

  it("allows LIMBO → ONLINE transition", () => {
    const sm = new GatewayStateMachine("LIMBO");
    expect(sm.transition("ONLINE")).toBe(true);
  });

  it("allows LIMBO → OFFLINE transition", () => {
    const sm = new GatewayStateMachine("LIMBO");
    expect(sm.transition("OFFLINE")).toBe(true);
  });

  it("allows OFFLINE → ONLINE transition", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    expect(sm.transition("ONLINE")).toBe(true);
  });

  it("rejects OFFLINE → LIMBO transition", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    const result = sm.transition("LIMBO");
    expect(result).toBe(false);
    expect(sm.getState()).toBe("OFFLINE");
  });

  it("rejects OFFLINE → UNKNOWN transition", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    expect(sm.transition("UNKNOWN")).toBe(false);
  });

  it("rejects ONLINE → ONLINE self-transition", () => {
    const sm = new GatewayStateMachine("ONLINE");
    expect(sm.transition("ONLINE")).toBe(false);
  });

  it("rejects ONLINE → OFFLINE transition", () => {
    const sm = new GatewayStateMachine("ONLINE");
    expect(sm.transition("OFFLINE")).toBe(false);
  });

  it("rejects LIMBO → UNKNOWN transition", () => {
    const sm = new GatewayStateMachine("LIMBO");
    expect(sm.transition("UNKNOWN")).toBe(false);
  });

  it("emits state_change on successful transition", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    const events: Array<{ from: string; to: string }> = [];
    sm.on("state_change", (entry) => events.push(entry));
    sm.transition("ONLINE");
    expect(events).toHaveLength(1);
    expect(events[0]!.from).toBe("UNKNOWN");
    expect(events[0]!.to).toBe("ONLINE");
  });

  it("does not emit state_change on rejected transition", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    const events: unknown[] = [];
    sm.on("state_change", (e) => events.push(e));
    sm.transition("LIMBO");
    expect(events).toHaveLength(0);
  });

  it("state_change event includes an ISO timestamp", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    let timestamp: string | undefined;
    sm.on("state_change", (entry: { timestamp: string }) => { timestamp = entry.timestamp; });
    sm.transition("ONLINE");
    expect(timestamp).toBeDefined();
    expect(() => new Date(timestamp!)).not.toThrow();
  });

  it("tracks transition history", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    sm.transition("ONLINE");
    sm.transition("LIMBO");
    const history = sm.getHistory();
    expect(history).toHaveLength(2);
    expect(history[0]!.from).toBe("UNKNOWN");
    expect(history[0]!.to).toBe("ONLINE");
    expect(history[1]!.from).toBe("ONLINE");
    expect(history[1]!.to).toBe("LIMBO");
  });

  it("getHistory returns a copy (mutations do not affect internal state)", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    sm.transition("ONLINE");
    const h = sm.getHistory();
    h.splice(0, 1);
    expect(sm.getHistory()).toHaveLength(1);
  });

  it("reports correct capabilities for ONLINE state", () => {
    const sm = new GatewayStateMachine("ONLINE");
    const caps = sm.getCapabilities();
    expect(caps.remoteOps).toBe(true);
    expect(caps.tynn).toBe(true);
    expect(caps.memory).toBe(true);
    expect(caps.deletions).toBe(true);
  });

  it("reports correct capabilities for LIMBO state", () => {
    const sm = new GatewayStateMachine("LIMBO");
    const caps = sm.getCapabilities();
    expect(caps.remoteOps).toBe(false);
    expect(caps.tynn).toBe(true);
    expect(caps.memory).toBe(true);
    expect(caps.deletions).toBe(false);
  });

  it("reports correct capabilities for OFFLINE state", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    const caps = sm.getCapabilities();
    expect(caps.remoteOps).toBe(false);
    expect(caps.tynn).toBe(false);
    expect(caps.memory).toBe(true);
    expect(caps.deletions).toBe(false);
  });

  it("reports correct capabilities for UNKNOWN state", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    const caps = sm.getCapabilities();
    expect(caps.remoteOps).toBe(false);
    expect(caps.tynn).toBe(false);
    expect(caps.memory).toBe(false);
    expect(caps.deletions).toBe(false);
  });

  it("isAllowed returns true for tynn when ONLINE", () => {
    const sm = new GatewayStateMachine("ONLINE");
    expect(sm.isAllowed("tynn")).toBe(true);
  });

  it("isAllowed returns false for deletions when OFFLINE", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    expect(sm.isAllowed("deletions")).toBe(false);
  });

  it("isAllowed returns false for memory when UNKNOWN", () => {
    const sm = new GatewayStateMachine("UNKNOWN");
    expect(sm.isAllowed("memory")).toBe(false);
  });

  it("isAllowed returns true for memory when OFFLINE", () => {
    const sm = new GatewayStateMachine("OFFLINE");
    expect(sm.isAllowed("memory")).toBe(true);
  });

  it("isAllowed returns false for remoteOps when LIMBO", () => {
    const sm = new GatewayStateMachine("LIMBO");
    expect(sm.isAllowed("remoteOps")).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 2. ChannelRegistry tests
// ---------------------------------------------------------------------------

describe.skip("ChannelRegistry", () => {
  let registry: ChannelRegistry;

  beforeEach(() => {
    registry = new ChannelRegistry();
  });

  it("registers a valid plugin without throwing", () => {
    const plugin = createMockPlugin("telegram");
    expect(() => registry.register(plugin)).not.toThrow();
  });

  it("getChannel returns the entry after registration", () => {
    const plugin = createMockPlugin("telegram");
    registry.register(plugin);
    const entry = registry.getChannel("telegram");
    expect(entry).toBeDefined();
    expect(entry!.plugin.id).toBe("telegram");
    expect(entry!.status).toBe("registered");
  });

  it("throws on duplicate registration of the same id", () => {
    registry.register(createMockPlugin("telegram"));
    expect(() => registry.register(createMockPlugin("telegram"))).toThrow(/already registered/);
  });

  it("throws on invalid adapter (missing required adapters)", () => {
    const invalid = { id: "bad" as ChannelId } as AionimaChannelPlugin;
    expect(() => registry.register(invalid)).toThrow();
  });

  it("starts a channel and transitions status to running", async () => {
    const plugin = createMockPlugin("telegram");
    registry.register(plugin);
    await registry.startChannel("telegram");
    expect(registry.getChannel("telegram")!.status).toBe("running");
    expect(plugin._test.isRunning()).toBe(true);
  });

  it("stops a running channel and transitions status to stopped", async () => {
    const plugin = createMockPlugin("telegram");
    registry.register(plugin);
    await registry.startChannel("telegram");
    await registry.stopChannel("telegram");
    expect(registry.getChannel("telegram")!.status).toBe("stopped");
    expect(plugin._test.isRunning()).toBe(false);
  });

  it("emits channel_registered event on registration", () => {
    const events: string[] = [];
    registry.on("channel_registered", (id) => events.push(id));
    registry.register(createMockPlugin("telegram"));
    expect(events).toEqual(["telegram"]);
  });

  it("emits channel_started event after successful start", async () => {
    const events: string[] = [];
    registry.on("channel_started", (id) => events.push(id));
    registry.register(createMockPlugin("telegram"));
    await registry.startChannel("telegram");
    expect(events).toEqual(["telegram"]);
  });

  it("emits channel_stopped event after successful stop", async () => {
    const events: string[] = [];
    registry.on("channel_stopped", (id) => events.push(id));
    registry.register(createMockPlugin("telegram"));
    await registry.startChannel("telegram");
    await registry.stopChannel("telegram");
    expect(events).toEqual(["telegram"]);
  });

  it("startChannel throws when channel id is not registered", async () => {
    await expect(registry.startChannel("nonexistent")).rejects.toThrow(/not registered/);
  });

  it("stopChannel throws when channel id is not registered", async () => {
    await expect(registry.stopChannel("nonexistent")).rejects.toThrow(/not registered/);
  });

  it("startAll starts all registered channels in parallel", async () => {
    const p1 = createMockPlugin("ch1");
    const p2 = createMockPlugin("ch2");
    registry.register(p1);
    registry.register(p2);
    await registry.startAll();
    expect(p1._test.isRunning()).toBe(true);
    expect(p2._test.isRunning()).toBe(true);
  });

  it("stopAll stops only running channels", async () => {
    const p1 = createMockPlugin("ch1");
    const p2 = createMockPlugin("ch2");
    registry.register(p1);
    registry.register(p2);
    // Only start ch1
    await registry.startChannel("ch1");
    await registry.stopAll();
    expect(p1._test.isRunning()).toBe(false);
    // ch2 was never started — its stop should not have been called
    expect(p2._test.isRunning()).toBe(false);
    expect(registry.getChannel("ch1")!.status).toBe("stopped");
    expect(registry.getChannel("ch2")!.status).toBe("registered");
  });

  it("unregister removes channel from registry", () => {
    registry.register(createMockPlugin("telegram"));
    registry.unregister("telegram");
    expect(registry.getChannel("telegram")).toBeUndefined();
  });

  it("unregister emits channel_unregistered", () => {
    const events: string[] = [];
    registry.on("channel_unregistered", (id) => events.push(id));
    registry.register(createMockPlugin("telegram"));
    registry.unregister("telegram");
    expect(events).toEqual(["telegram"]);
  });

  it("unregister is a no-op for unknown id", () => {
    expect(() => registry.unregister("nonexistent")).not.toThrow();
  });

  it("getChannels returns all registered entries", () => {
    registry.register(createMockPlugin("ch1"));
    registry.register(createMockPlugin("ch2"));
    expect(registry.getChannels()).toHaveLength(2);
  });

  it("getRunningChannels returns only running entries", async () => {
    registry.register(createMockPlugin("ch1"));
    registry.register(createMockPlugin("ch2"));
    await registry.startChannel("ch1");
    const running = registry.getRunningChannels();
    expect(running).toHaveLength(1);
    expect(running[0]!.plugin.id).toBe("ch1");
  });

  it("registeredAt is an ISO timestamp", () => {
    const before = new Date().toISOString();
    registry.register(createMockPlugin("telegram"));
    const after = new Date().toISOString();
    const entry = registry.getChannel("telegram")!;
    expect(entry.registeredAt >= before).toBe(true);
    expect(entry.registeredAt <= after).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 3. InboundRouter tests
// ---------------------------------------------------------------------------

describe.skip("InboundRouter", () => {
  let db: Database;
  let entityStore: EntityStore;
  let messageQueue: MessageQueue;
  let mockCOA: ReturnType<typeof createMockCOALogger>;
  let router: InboundRouter;

  beforeEach(() => {
    db = createTestDb();
    entityStore = new EntityStore(db);
    messageQueue = new MessageQueue(db);
    mockCOA = createMockCOALogger();
    router = new InboundRouter({
      entityStore,
      messageQueue,
      coaLogger: mockCOA.logger,
      resourceId: "$A0",
      nodeId: "@A0",
    });
  });

  it("routes a message and returns entityId, coaFingerprint, and queueMessageId", async () => {
    const msg = makeAionimaMessage("telegram", "user-001");
    const result = (await router.route(msg))!;
    expect(typeof result.entityId).toBe("string");
    expect(result.entityId.length).toBeGreaterThan(0);
    expect(typeof result.coaFingerprint).toBe("string");
    expect(result.coaFingerprint.length).toBeGreaterThan(0);
    expect(typeof result.queueMessageId).toBe("string");
    expect(result.queueMessageId.length).toBeGreaterThan(0);
  });

  it("creates a new entity if none exists for the channel user", async () => {
    const msg = makeAionimaMessage("telegram", "new-user");
    const result = (await router.route(msg))!;
    const entity = entityStore.getEntity(result.entityId);
    expect(entity).not.toBeNull();
    expect(entity!.type).toBe("E");
  });

  it("reuses existing entity on subsequent messages from same user", async () => {
    const msg1 = makeAionimaMessage("telegram", "user-001", "first");
    const msg2 = makeAionimaMessage("telegram", "user-001", "second");
    const r1 = (await router.route(msg1))!;
    const r2 = (await router.route(msg2))!;
    expect(r1.entityId).toBe(r2.entityId);
  });

  it("returns a pending COA fingerprint for deferred logging", async () => {
    // COA entry is NOT created at route time — it's created when the agent
    // COMPLETES its response (agent-invoker.ts). The fingerprint is a
    // placeholder in the format: $resourceId.#coaAlias.@nodeId.pending
    const msg = makeAionimaMessage("telegram", "user-coa");
    const result = (await router.route(msg))!;
    expect(result.coaFingerprint).toContain(".pending");
    expect(result.coaFingerprint).toContain("$A0");
    expect(result.coaFingerprint).toContain("@A0");
  });

  it("enqueues message as inbound in the message queue", async () => {
    const msg = makeAionimaMessage("telegram", "user-queue");
    const result = (await router.route(msg))!;
    // Queue depth should be 1 (message is pending)
    expect(messageQueue.depth("inbound")).toBe(1);
    // The enqueued message id matches
    const peeked = messageQueue.peek("inbound");
    expect(peeked[0]!.id).toBe(result.queueMessageId);
  });

  it("different channel users produce different entity IDs", async () => {
    const msg1 = makeAionimaMessage("telegram", "user-A");
    const msg2 = makeAionimaMessage("telegram", "user-B");
    const r1 = (await router.route(msg1))!;
    const r2 = (await router.route(msg2))!;
    expect(r1.entityId).not.toBe(r2.entityId);
  });

  it("COA fingerprint is a non-empty placeholder string", async () => {
    const msg = makeAionimaMessage("telegram", "user-fp");
    const result = (await router.route(msg))!;
    expect(result.coaFingerprint.length).toBeGreaterThan(0);
    // Fingerprint is a placeholder — actual COA record created at agent completion
    expect(result.coaFingerprint).toMatch(/\$A0\..*\.@A0\.pending/);
  });
});

// ---------------------------------------------------------------------------
// 4. OutboundDispatcher tests
// ---------------------------------------------------------------------------

describe.skip("OutboundDispatcher", () => {
  let mockCOA: ReturnType<typeof createMockCOALogger>;
  let plugin: ReturnType<typeof createMockPlugin>;
  let dispatcher: OutboundDispatcher;

  // A fixed entity ID string — OutboundDispatcher only passes it to coaLogger;
  // with the mock logger there is no entity format constraint.
  const TEST_ENTITY_ID = "entity-out-test";

  beforeEach(() => {
    mockCOA = createMockCOALogger();
    plugin = createMockPlugin("telegram");

    dispatcher = new OutboundDispatcher({
      getChannelAdapter: (id) => id === "telegram" ? plugin.outbound : undefined,
      coaLogger: mockCOA.logger,
      resolveCoaAlias: (entityId) => `#MOCK-${entityId}`,
      resourceId: "$A0",
      nodeId: "@A0",
    });
  });

  it("dispatches a single message to the correct channel adapter", async () => {
    const route: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-001",
      content: { type: "text", text: "Hello!" },
      entityId: TEST_ENTITY_ID,
    };

    const result = await dispatcher.dispatch(route);
    expect(result.channelId).toBe("telegram");
    expect(result.channelUserId).toBe("user-001");
    expect(plugin._test.sentMessages).toHaveLength(1);
    expect(plugin._test.sentMessages[0]!.userId).toBe("user-001");
  });

  it("throws if channel adapter not found", async () => {
    const route: OutboundRoute = {
      channelId: "discord",
      channelUserId: "user-001",
      content: { type: "text", text: "Hello!" },
      entityId: TEST_ENTITY_ID,
    };
    await expect(dispatcher.dispatch(route)).rejects.toThrow(/Channel not found/);
  });

  it("returns a delivered COA fingerprint placeholder", async () => {
    // COA entry is created at invocation DONE, not per outbound message.
    // The fingerprint is a placeholder: $resourceId.#alias.@nodeId.delivered
    const route: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-001",
      content: { type: "text", text: "COA test" },
      entityId: TEST_ENTITY_ID,
    };

    const result = await dispatcher.dispatch(route);
    expect(result.coaFingerprint).toBeDefined();
    expect(result.coaFingerprint).toContain(".delivered");
    expect(result.coaFingerprint).toContain("$A0");
  });

  it("returns a deliveredAt ISO timestamp", async () => {
    const route: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-001",
      content: { type: "text", text: "time test" },
      entityId: TEST_ENTITY_ID,
    };

    const result = await dispatcher.dispatch(route);
    expect(() => new Date(result.deliveredAt)).not.toThrow();
  });

  it("dispatchBatch processes multiple routes", async () => {
    const routes: OutboundRoute[] = [
      { channelId: "telegram", channelUserId: "u1", content: { type: "text", text: "msg1" }, entityId: TEST_ENTITY_ID },
      { channelId: "telegram", channelUserId: "u2", content: { type: "text", text: "msg2" }, entityId: TEST_ENTITY_ID },
    ];

    const batch = await dispatcher.dispatchBatch(routes);
    expect(batch.successCount).toBe(2);
    expect(batch.failureCount).toBe(0);
    expect(plugin._test.sentMessages).toHaveLength(2);
  });

  it("dispatchBatch reports individual failures without aborting", async () => {
    const routes: OutboundRoute[] = [
      { channelId: "telegram", channelUserId: "u1", content: { type: "text", text: "ok" }, entityId: TEST_ENTITY_ID },
      // discord is not registered — will fail
      { channelId: "discord", channelUserId: "u2", content: { type: "text", text: "fail" }, entityId: TEST_ENTITY_ID },
    ];

    const batch = await dispatcher.dispatchBatch(routes);
    expect(batch.successCount).toBe(1);
    expect(batch.failureCount).toBe(1);
    // telegram message was still sent
    expect(plugin._test.sentMessages).toHaveLength(1);
  });
});

// ---------------------------------------------------------------------------
// 5. QueueConsumer tests
// ---------------------------------------------------------------------------

describe.skip("QueueConsumer", () => {
  // These tests use real timers throughout. QueueConsumer uses setInterval
  // internally; fake timers in pool:forks mode interfere with async settling.
  let db: Database;
  let messageQueue: MessageQueue;
  let plugin: ReturnType<typeof createMockPlugin>;
  let dispatcher: OutboundDispatcher;
  let mockCOA: ReturnType<typeof createMockCOALogger>;

  beforeEach(() => {
    db = createTestDb();
    messageQueue = new MessageQueue(db);
    mockCOA = createMockCOALogger();
    plugin = createMockPlugin("telegram");
    dispatcher = new OutboundDispatcher({
      getChannelAdapter: (id) => id === "telegram" ? plugin.outbound : undefined,
      coaLogger: mockCOA.logger,
      resolveCoaAlias: (entityId) => `#MOCK-${entityId}`,
      resourceId: "$A0",
      nodeId: "@A0",
    });
  });

  it("starts polling (isRunning returns true after start)", async () => {
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 100 },
    );
    consumer.start();
    expect(consumer.isRunning()).toBe(true);
    await consumer.stop();
  });

  it("start is a no-op if already running", async () => {
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 100 },
    );
    consumer.start();
    consumer.start(); // second call — no-op
    expect(consumer.isRunning()).toBe(true);
    await consumer.stop();
  });

  it("stop sets isRunning to false", async () => {
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 100 },
    );
    consumer.start();
    await consumer.stop();
    expect(consumer.isRunning()).toBe(false);
  });

  it("processes inbound messages from the queue", async () => {
    const received: QueueMessage[] = [];
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async (msg) => { received.push(msg); } },
      { pollIntervalMs: 50, concurrency: 10 },
    );

    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: { text: "hi" } });

    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    expect(received).toHaveLength(1);
    expect((received[0]!.payload as { text: string }).text).toBe("hi");
  });

  it("processes outbound messages via OutboundDispatcher", async () => {
    // Use a fixed entity ID — mock COA logger accepts any ID
    const outboundRoute: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-out",
      content: { type: "text", text: "outbound!" },
      entityId: "entity-consumer-test",
    };

    messageQueue.enqueue({ channel: "telegram", direction: "outbound", payload: outboundRoute });

    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 50, concurrency: 10 },
    );

    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    expect(plugin._test.sentMessages).toHaveLength(1);
    expect(plugin._test.sentMessages[0]!.userId).toBe("user-out");
  });

  it("marks messages as complete on success", async () => {
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 50, concurrency: 10 },
    );

    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    // After processing, pending depth should be 0 (message moved to done)
    expect(messageQueue.depth("inbound")).toBe(0);
  });

  it("marks messages as failed on error", async () => {
    // Use maxRetries: 1 so the message goes to dead-letter after a single
    // failure rather than being re-enqueued and failing multiple times.
    const singleRetryQueue = new MessageQueue(db, { maxRetries: 1 });
    const consumer = new QueueConsumer(
      {
        messageQueue: singleRetryQueue,
        outboundDispatcher: dispatcher,
        onInbound: async () => { throw new Error("processing error"); },
      },
      { pollIntervalMs: 50, concurrency: 10 },
    );

    singleRetryQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    expect(consumer.getStats().failed).toBe(1);
  });

  it("respects concurrency limit (inFlight does not exceed concurrency)", async () => {
    let maxInFlight = 0;
    let currentInFlight = 0;
    const concurrency = 2;

    const consumer = new QueueConsumer(
      {
        messageQueue,
        outboundDispatcher: dispatcher,
        onInbound: async () => {
          currentInFlight++;
          maxInFlight = Math.max(maxInFlight, currentInFlight);
          await new Promise((r) => setTimeout(r, 20));
          currentInFlight--;
        },
      },
      { pollIntervalMs: 10, concurrency },
    );

    // Enqueue 5 messages
    for (let i = 0; i < 5; i++) {
      messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: { i } });
    }

    consumer.start();
    await new Promise((r) => setTimeout(r, 400));
    await consumer.stop();

    expect(maxInFlight).toBeLessThanOrEqual(concurrency);
  });

  it("emits message_processed on success", async () => {
    const events: Array<{ id: string; direction: string }> = [];
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 50, concurrency: 10 },
    );
    consumer.on("message_processed", (e) => events.push(e));

    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    expect(events).toHaveLength(1);
    expect(events[0]!.direction).toBe("inbound");
  });

  it("emits message_failed on error", async () => {
    // Use maxRetries: 1 so the message fails exactly once before dead-letter.
    const singleRetryQueue = new MessageQueue(db, { maxRetries: 1 });
    const failures: Array<{ id: string; direction: string; error: string }> = [];
    const consumer = new QueueConsumer(
      {
        messageQueue: singleRetryQueue,
        outboundDispatcher: dispatcher,
        onInbound: async () => { throw new Error("boom"); },
      },
      { pollIntervalMs: 50, concurrency: 10 },
    );
    consumer.on("message_failed", (e) => failures.push(e));

    singleRetryQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    expect(failures).toHaveLength(1);
    expect(failures[0]!.error).toContain("boom");
  });

  it("emits drain_complete when stopped", async () => {
    let drainFired = false;
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 50 },
    );
    consumer.on("drain_complete", () => { drainFired = true; });
    consumer.start();
    await consumer.stop();
    expect(drainFired).toBe(true);
  });

  it("getStats returns accurate counts", async () => {
    const consumer = new QueueConsumer(
      { messageQueue, outboundDispatcher: dispatcher, onInbound: async () => {} },
      { pollIntervalMs: 50, concurrency: 10 },
    );

    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });
    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: {} });

    consumer.start();
    await new Promise((r) => setTimeout(r, 300));
    await consumer.stop();

    const stats = consumer.getStats();
    expect(stats.processed).toBe(2);
    expect(stats.failed).toBe(0);
    expect(stats.isRunning).toBe(false);
  });

  it("graceful shutdown drains in-flight messages", async () => {
    const processed: string[] = [];
    const consumer = new QueueConsumer(
      {
        messageQueue,
        outboundDispatcher: dispatcher,
        onInbound: async (msg) => {
          await new Promise((r) => setTimeout(r, 30));
          processed.push(msg.id);
        },
      },
      { pollIntervalMs: 50, concurrency: 10, drainTimeoutMs: 2000 },
    );

    messageQueue.enqueue({ channel: "telegram", direction: "inbound", payload: { n: 1 } });

    consumer.start();
    // Let the poll tick fire and message start processing
    await new Promise((r) => setTimeout(r, 80));
    // Stop while message is in-flight — drain should wait for it
    await consumer.stop();

    // After drain, the message should have been processed
    expect(processed.length).toBeGreaterThanOrEqual(1);
  });
});

// ---------------------------------------------------------------------------
// 6. End-to-End Integration tests
// ---------------------------------------------------------------------------

describe.skip("Gateway E2E", () => {
  // Uses the mock COA logger to avoid entity ID format constraints while
  // still testing the full routing pipeline end-to-end.
  let db: Database;
  let entityStore: EntityStore;
  let messageQueue: MessageQueue;
  let mockCOA: ReturnType<typeof createMockCOALogger>;
  let plugin: ReturnType<typeof createMockPlugin>;
  let router: InboundRouter;
  let dispatcher: OutboundDispatcher;

  beforeEach(() => {
    db = createTestDb();
    entityStore = new EntityStore(db);
    messageQueue = new MessageQueue(db);
    mockCOA = createMockCOALogger();
    plugin = createMockPlugin("telegram");

    router = new InboundRouter({
      entityStore,
      messageQueue,
      coaLogger: mockCOA.logger,
      resourceId: "$A0",
      nodeId: "@A0",
    });

    dispatcher = new OutboundDispatcher({
      getChannelAdapter: (id) => id === "telegram" ? plugin.outbound : undefined,
      coaLogger: mockCOA.logger,
      resolveCoaAlias: (entityId) => `#MOCK-${entityId}`,
      resourceId: "$A0",
      nodeId: "@A0",
    });
  });

  it("full inbound pipeline: InboundRouter creates entity + COA + enqueue, QueueConsumer delivers to onInbound", async () => {
    const receivedMessages: QueueMessage[] = [];

    const consumer = new QueueConsumer(
      {
        messageQueue,
        outboundDispatcher: dispatcher,
        onInbound: async (msg) => { receivedMessages.push(msg); },
      },
      { pollIntervalMs: 50, concurrency: 5 },
    );

    // Simulate inbound message from channel adapter
    const msg = makeAionimaMessage("telegram", "user-e2e", "Hello, Aionima!");
    const routeResult = (await router.route(msg))!;

    // Verify entity was created in the store
    const entity = entityStore.getEntity(routeResult.entityId);
    expect(entity).not.toBeNull();

    // COA is deferred to agent completion — verify placeholder fingerprint
    expect(routeResult.coaFingerprint).toContain(".pending");

    // Verify message was enqueued
    expect(messageQueue.depth("inbound")).toBe(1);

    // Start consumer and let it drain
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    // onInbound should have been called
    expect(receivedMessages).toHaveLength(1);
    const payload = receivedMessages[0]!.payload as { entityId: string; coaFingerprint: string };
    expect(payload.entityId).toBe(routeResult.entityId);
    expect(payload.coaFingerprint).toBe(routeResult.coaFingerprint);
  });

  it("outbound pipeline: enqueue outbound → QueueConsumer dequeues → OutboundDispatcher → adapter.send called", async () => {
    const consumer = new QueueConsumer(
      {
        messageQueue,
        outboundDispatcher: dispatcher,
        onInbound: async () => {},
      },
      { pollIntervalMs: 50, concurrency: 5 },
    );

    // Enqueue an outbound route directly — mock COA accepts any entity ID
    const outboundRoute: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-e2e-out",
      content: { type: "text", text: "Outbound E2E message" },
      entityId: "e2e-entity-out",
    };

    messageQueue.enqueue({ channel: "telegram", direction: "outbound", payload: outboundRoute });

    // Start consumer and drain
    consumer.start();
    await new Promise((r) => setTimeout(r, 200));
    await consumer.stop();

    // Adapter send should have been called
    expect(plugin._test.sentMessages).toHaveLength(1);
    expect(plugin._test.sentMessages[0]!.userId).toBe("user-e2e-out");
    expect((plugin._test.sentMessages[0]!.content as { type: string; text: string }).text).toBe("Outbound E2E message");
  });

  it("bidirectional pipeline: inbound triggers entity creation, subsequent outbound reuses entity", async () => {
    const inboundMsg = makeAionimaMessage("telegram", "user-bidir", "ping");
    const routeResult = (await router.route(inboundMsg))!;

    // Verify entity was created
    const entity = entityStore.getEntity(routeResult.entityId);
    expect(entity).not.toBeNull();

    // Send outbound to same entity (mock COA logs it without format constraint)
    const outboundRoute: OutboundRoute = {
      channelId: "telegram",
      channelUserId: "user-bidir",
      content: { type: "text", text: "pong" },
      entityId: routeResult.entityId,
    };

    const result = await dispatcher.dispatch(outboundRoute);
    expect(result.channelUserId).toBe("user-bidir");
    expect(plugin._test.sentMessages[0]!.userId).toBe("user-bidir");

    // COA is deferred — both inbound and outbound return placeholder fingerprints
    expect(routeResult.coaFingerprint).toContain(".pending");
    expect(result.coaFingerprint).toContain(".delivered");
  });

  it("multiple users produce isolated entity records", async () => {
    const msg1 = makeAionimaMessage("telegram", "user-alpha");
    const msg2 = makeAionimaMessage("telegram", "user-beta");

    const r1 = (await router.route(msg1))!;
    const r2 = (await router.route(msg2))!;

    expect(r1.entityId).not.toBe(r2.entityId);

    const entities = entityStore.listEntities();
    expect(entities).toHaveLength(2);
  });
});
