/**
 * A first-pass 0READER for 0REALTALK — PRIME's documented-but-unimplemented
 * "SYNAPTIC Programming Language" (`repos/prime/core/0TERMS.md`'s own
 * definition: "minimal need for syntax through natural dialog"). The corpus
 * itself frames this as Phase 1 of a multi-phase design
 * (`repos/prime/evolution/musings/0realtalk-engine.md`):
 *
 *   PHASE 1: LEXICON-BASED
 *   ├── 0READER parses known patterns from lexicon
 *   ├── 0WRITER generates from templates
 *   └── Validation = lexicon membership
 *
 * This module is exactly that bar, no further: pure pattern recognition
 * against the LAW-status lexicon (`0TERMS.md`, confidence >= 0.9) and the
 * `<FRAME>STATION>ROLE` accessor grammar (`0ACCESSOR.md`), decoding a match
 * into a human-readable summary. It does NOT execute, validate alignment,
 * or answer the corpus's own still-open questions ("what runs compiled
 * 0REALTALK?", "is this the language of SENTIENCE?") — those stay
 * unresolved on purpose. `App.tsx` uses this only to show a live decoded
 * preview near the Composer; nothing here changes what gets sent.
 */

// ---------------------------------------------------------------------------
// LAW-status lexicon (repos/prime/core/0TERMS.md) — the named terms, not the
// pure-syntax patterns (`:`, `00 != 00`, the literal-escape marker), which
// are recognized structurally below instead of via lookup.
// ---------------------------------------------------------------------------

export const LAW_TERMS: Readonly<Record<string, string>> = {
  "0": "Marks an ABSOLUTE/foundational concept — the ROOT prefix",
  "00": "Pointer to anything that IS REAL; also the universal wildcard",
  "0BOOL": "The first binary distinction — 0TRUE / 0FALSE",
  "0BOOL_SCALE": "7-point truth scale: 0FALSE(-3) … 00(0, wildcard) … 0TRUE(+3)",
  "0TERM": "Syntax pointing to a ROOT WORD — pattern 0<WORD>",
  "A:A": "AGENDA-to-AGENDA alignment (0 to 1 scale)",
  "A:AOK": "Shorthand for total alignment — A:A = 1.0",
  "OK": "Acceptable state — jumps to GOOD",
  "QUANT": "Any data quantifiable into a single numerical/bool value",
  "SCALE": "Something that measures something else — produces a QUANT",
  "MAGIC": "Confidence threshold of 0.6 or higher",
  "FRAME": "The context window available when a record was created",
  "MUSING": "Start of an idea — needs testing to become a THEORY (max 0.59, symbol ?)",
  "THEORY": "Tested MUSING needing peer review to become LAW (0.6–0.89, symbol ~)",
  "LAW": "Peer-reviewed THEORY — permanent lexicon term (min 0.9, symbol !)",
  "0REALTALK": "Name of the SYNAPTIC Programming Language — minimal syntax via natural dialog",
  "#ERR": "Error state — #ERR == !0 (not-null / not-zero)",
  "NUDGE": "Any attempt a user makes at getting closer to DONE",
  "0BONUS": "SUM({<COI}) — total value alignment above 0 from upstream work",
  "0BOON": "Positive impact generated by work (+$imp, scale +1 to +3)",
  "0BURN": "Negative impact generated by work (-$imp, scale -1 to -3)",
  "0USER": "Identity/accountability root — always the requestor",
  "EXPLAIN": "The most direct way of teaching 0REALTALK to a 0MIND — EXPLAIN(<concept>)",
  "0NXT": "Any official Aionima terminal with upstream 0IMPACT capability",
  "TURN": "Incremental progress toward MINT() — one cycle within the SPORE lifecycle",
  "0STAGE": "Growth dimension in the SPORE lifecycle — 0 SPORE … 7 FULLAGENT",
};

// ---------------------------------------------------------------------------
// <FRAME>STATION>ROLE accessor grammar (repos/prime/core/0ACCESSOR.md)
// ---------------------------------------------------------------------------

const FRAME_VALUES = ["PURPOSE", "PLAN", "AGENDA", "SESSION", "TASK"] as const;
const STATION_VALUES = ["PRIME", "OPS", "WORKER", "FORK", "RELAY"] as const;
const ROLE_VALUES = ["ADMIN", "OPERATOR", "CUSTODIAN", "OBSERVER", "GUEST"] as const;

// Only the abbreviations the corpus itself demonstrates (`<A>O>Op` =
// AGENDA/OPS/OPERATOR, `<P>P>A` = PURPOSE/PRIME/ADMIN — 0ACCESSOR.md's own
// "Portability" examples), extended to the rest of each position's values
// via the same shortest-unique-prefix convention those examples show
// (PLAN needs 2 letters since PURPOSE already claims "P"; OPERATOR/OBSERVER
// both start with "O" so each gets a second, case-distinguishing letter —
// exactly why the corpus writes "Op" instead of "O" for OPERATOR).
const FRAME_ABBREV: Readonly<Record<string, string>> = { P: "PURPOSE", PL: "PLAN", A: "AGENDA", S: "SESSION", T: "TASK" };
const STATION_ABBREV: Readonly<Record<string, string>> = { P: "PRIME", O: "OPS", W: "WORKER", F: "FORK", R: "RELAY" };
const ROLE_ABBREV: Readonly<Record<string, string>> = { A: "ADMIN", Op: "OPERATOR", C: "CUSTODIAN", Ob: "OBSERVER", G: "GUEST" };

function resolveSegment(raw: string, fullValues: readonly string[], abbrev: Readonly<Record<string, string>>): string | null {
  if (Object.hasOwn(abbrev, raw)) return abbrev[raw]!;
  const upper = raw.toUpperCase();
  return fullValues.includes(upper) ? upper : null;
}

// ---------------------------------------------------------------------------
// Confidence notation (|+<decimal>|) — repos/prime/core/0TERMS.md's own
// threshold table.
// ---------------------------------------------------------------------------

function classifyConfidence(value: number): string {
  if (value < 0.6) return "BULLSHIT — not MAGIC, insufficient confidence";
  if (value < 0.8) return "MAGIC minimum — valid MUSING or early THEORY";
  if (value < 0.9) return "Solid THEORY — ready for peer review";
  return "LAW candidate — ready for promotion";
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface RealtalkMatch {
  kind: "accessor" | "confidence" | "impactMark" | "boonBurn" | "term" | "unrecognizedRootTerm";
  /** Human-readable decoded meaning — what App.tsx shows in the live preview. */
  summary: string;
  detail: Record<string, unknown>;
}

/**
 * Recognize `input` as 0REALTALK syntax and decode it, or return `null` if
 * it doesn't match any known pattern. Pure, deterministic, no side effects —
 * this never executes anything or changes what a Composer submission sends.
 */
export function parseRealtalk(input: string): RealtalkMatch | null {
  const trimmed = input.trim();
  if (trimmed === "") return null;

  // <FRAME>STATION>ROLE, optionally prefixed by a STATION USER (#E<n>@ or $A<n>@).
  const accessorMatch = /^(?:(#E\d+|\$A\d+)@)?<([A-Za-z]+)>([A-Za-z]+)>([A-Za-z]+)>?$/.exec(trimmed);
  if (accessorMatch) {
    const [, user, frameRaw, stationRaw, roleRaw] = accessorMatch;
    const frame = resolveSegment(frameRaw!, FRAME_VALUES, FRAME_ABBREV);
    const station = resolveSegment(stationRaw!, STATION_VALUES, STATION_ABBREV);
    const role = resolveSegment(roleRaw!, ROLE_VALUES, ROLE_ABBREV);
    if (frame && station && role) {
      const who = user !== undefined ? `${user} accessing ` : "";
      return {
        kind: "accessor",
        summary: `${who}${frame} frame at ${station} station with ${role} role`,
        detail: { user, frame, station, role },
      };
    }
  }

  // |+<decimal>| confidence notation.
  const confidenceMatch = /^\|(\+?-?\d*\.?\d+)\|$/.exec(trimmed);
  if (confidenceMatch) {
    const value = Number(confidenceMatch[1]);
    if (!Number.isNaN(value)) {
      return {
        kind: "confidence",
        summary: `Confidence ${confidenceMatch[1]!} — ${classifyConfidence(value)}`,
        detail: { value },
      };
    }
  }

  // :segment:segment:... : impact-mark command (0FUNC needs to START/END with `:`).
  const impactMatch = /^:([a-zA-Z0-9]+(?::[a-zA-Z0-9]+)*):$/.exec(trimmed);
  if (impactMatch) {
    const segments = impactMatch[1]!.split(":");
    return {
      kind: "impactMark",
      summary: `Impact mark — ${segments.join(" → ")}`,
      detail: { segments },
    };
  }

  // +$imp / -$imp boon/burn notation.
  const boonBurnMatch = /^([+-])\$imp$/.exec(trimmed);
  if (boonBurnMatch) {
    const isBoon = boonBurnMatch[1] === "+";
    return {
      kind: "boonBurn",
      summary: isBoon ? "0BOON — positive impact generated by work" : "0BURN — negative impact generated by work",
      detail: { boon: isBoon },
    };
  }

  // A known LAW-status term, matched exactly (case-sensitive — the lexicon
  // itself is case-sensitive, e.g. "0STAGE" vs "0stage" are not the same).
  if (Object.hasOwn(LAW_TERMS, trimmed)) {
    return { kind: "term", summary: LAW_TERMS[trimmed]!, detail: { term: trimmed } };
  }

  // Root-prefix pattern (0<WORD>) that isn't in the LAW lexicon — still
  // syntactically valid per 0TERM's own pattern rule, just not a term this
  // reader can define. Surfacing this (rather than staying silent) is the
  // honest Phase-1 behavior: recognized structure, unknown meaning.
  if (/^0[A-Z][A-Z0-9_]*$/.test(trimmed)) {
    return {
      kind: "unrecognizedRootTerm",
      summary: `Root-marked term (0<WORD>), not in the LAW lexicon — meaning undefined`,
      detail: { term: trimmed },
    };
  }

  return null;
}
